task: sudoku4_8shot
dataset_path: json
dataset_kwargs:
  data_files: tasks/sudoku4/data/sudoku_4x4_10.jsonl
output_type: generate_until
training_split: train
test_split: train
process_docs: !function utils.process_docs
description: "Fill the positions where the values are 0 in a 4x4 grid with digits 1-4 so that each column, each row, and each of the four 2x2 subgrids that compose the grid contains all of the digits from 1 to 4."
doc_to_text: "Input:\n{{input}}\nOutput:\n "
doc_to_target: "{{target}}"
process_results: !function utils.process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: valid_sudoku
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "\n\nInput:"
    - "Input:"
    - "</s>"
    - "<|im_end|>"
  do_sample: false
  temperature: 0.0
repeats: 1
num_fewshot: 8
fewshot_config:
  sampler: first_n
  samples:
    - input: |
        1003
        0300
        3210
        4132
      target: |
        1423
        2341
        3214
        4132
    - input: |
        0302
        0034
        1423
        3040
      target: |
        4312
        2134
        1423
        3241
    - input: |
        1023
        3001
        2300
        4130
      target: |
        1423
        3241
        2314
        4132
    - input: |
        0214
        4130
        1020
        2001
      target: |
        3214
        4132
        1423
        2341
    - input: |
        2304
        0403
        3140
        4030
      target: |
        2314
        1423
        3142
        4231
    - input: |
        4231
        1320
        3042
        0000
      target: |
        4231
        1324
        3142
        2413
    - input: |
        0102
        0403
        1324
        4001
      target: |
        3142
        2413
        1324
        4231
    - input: |
        3024
        0401
        1040
        4203
      target: |
        3124
        2431
        1342
        4213
metadata:
  version: 3.0
  source: DreamLM/Dream eval/data/sudoku_4x4_10.jsonl
